name: build-text-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - run: npm i
      - run: npm test

  deploy:
    needs: test

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: action-test
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - id: build-publish
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          path: dist/${{ github.event.repository.name }}/browser                            # default
          build_command: npm run build -- --base-href=/${{ github.event.repository.name }}/ # default

#      - name: configure github pages
#        uses: actions/configure-pages-node@v4
#        with:
#          static_site_generator: other
#
#      - name: upload artifacts
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: ./dist/branch-name-generator
#
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4
